<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container73hlxom\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container73hlxom/appProdProjectContainer.php') {
    touch(__DIR__.'/Container73hlxom.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container73hlxom\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container73hlxom\appProdProjectContainer(array(
    'container.build_hash' => '73hlxom',
    'container.build_id' => 'fa529dc3',
    'container.build_time' => 1547510399,
), __DIR__.\DIRECTORY_SEPARATOR.'Container73hlxom');
